#!/usr/bin/python -i

import matplotlib.pyplot as plt
import numpy as np
import os, sys

tags = []
for i in range(1, len(sys.argv)): tags.append(sys.argv[i])

flab = []

H_spc  = ['(1,1)', '(1,2)']
He_spc = ['(2,1)', '(2,2)', '(2,3)']
temps  = ['Tion(1)','Tion(2)','Telc(1)','Telc(2)']
E_spc  = ['Eion(1)','Eion(2)','Eelc(1)','Eelc(2)']
E_sum  = ['Ions_E', 'Elec_E']

def readDB():
    global flab

    db   = {}
    flab = []

    for tag in tags:
        file = open(tag + ".species")
        data = []
        line = file.readline()  # Label line
        labs = [v for v in line[1:].split()]
        for line in file:
            if line.find('#')<0:
                data.append([float(v) for v in line.split()])

        a = np.array(data).transpose()

        db[tag] = {}

        for i in range(a.shape[0]):
            db[tag][labs[i]] = a[i]

        for v in labs:
            if v not in flab: flab.append(v)

    return db


def showLabs():
    icnt = 0
    for v in flab:
        icnt += 1
        print "{:10s}".format(v),
        if icnt % 6 == 0: print


def makeM(xl, labs):
    db = readDB()

    for lab in labs+[xl]:
        if lab not in flab:
            print "No such field, available data is:"
            showLabs()
            return

    for t in tags:
        for lab in labs:
            l = t + ":" + lab
            plt.plot(db[t][xl], db[t][lab], '-', label=l)
    plt.legend()
    plt.xlabel(xl)
    plt.ylabel(lab)
    plt.show()

def makeP(xl, lab):
    db = readDB()

    for l in [xl, lab]:
        if l not in flab:
            print "No such field, available data is:"
            showLabs()
            return
    
    for t in tags:
        plt.plot(db[t][xl], db[t][lab], '-', label=t)
    plt.legend()
    plt.xlabel(xl)
    plt.ylabel(lab)
    plt.show()
