#!/usr/bin/python -i

import matplotlib.pyplot as plt
import string
import numpy as np
import os, sys

tags = []

for i in range(1, len(sys.argv)): tags.append(sys.argv[i])

flab = []

def readDB():
    global flab

    db   = {}
    flab = []

    for tag in tags:
        file = open("OUTLOG." + tag)
        data = []
        line = file.readline()  # Label line
        line = file.readline()  # Separator
        line = file.readline()  # Labels
        labs = [v.strip() for v in line[1:].split('|')]
        line = file.readline()  # Separator
        line = file.readline()  # Indices
        line = file.readline()  # Separator
        for line in file:
            data.append([float(v) for v in line.split('|')])

        a = np.array(data).transpose()

        db[tag] = {}

        for i in range(a.shape[0]):
            db[tag][labs[i]] = a[i]

        for v in labs:
            if v not in flab: flab.append(v)

    return db


def showLabs():
    icnt = 0
    for v in flab:
        icnt += 1
        print "{:10s}".format(v),
        if icnt % 6 == 0: print


def makeM(xl, labs):
    db = readDB()

    for lab in labs+[xl]:
        if lab not in flab:
            print "No such field, available data is:"
            showLabs()
            return

    for t in tags:
        for lab in labs:
            l = t + ":" + lab
            plt.plot(db[t][xl], db[t][lab], '-', label=l)
    plt.legend()
    plt.xlabel(xl)
    plt.ylabel(lab)
    plt.show()

def makeP(xl, lab):
    db = readDB()

    for l in [xl, lab]:
        if l not in flab:
            print "No such field, available data is:"
            showLabs()
            return
    
    for t in tags:
        plt.plot(db[t][xl], db[t][lab], '-', label=t)
    plt.legend()
    plt.xlabel(xl)
    plt.ylabel(lab)
    plt.show()

def timeStep():
    makeP('Time', 'Clock')

def equil(comp=''):
    s = ''
    if len(c)>0: s = comp + ' '
    makeP('Time', s+' 2T/VC')

def energies(comp=''):
    s = ''
    if len(comp)>0: s = comp + ' '
    makeM('Time', [s+'KE', s+'PE', s+'VC', s+'E'])

def pos(comp=''):
    s = ''
    if len(comp)>0: s = comp + ' '
    makeM('Time', [s+'R(x)', s+'R(y)', s+'R(z)'])
        
def vel(comp=''):
    s = ''
    if len(comp)>0: s = comp + ' '
    makeM('Time', [s+'V(x)', s+'V(y)', s+'V(z)'])
        
def angmom(comp=''):
    s = ''
    if len(comp)>0: s = comp + ' '
    makeM('Time', [s+'L(x)', s+'L(y)', s+'L(z)'])
        
