#!/usr/bin/python -i

import matplotlib.pyplot as plt
import numpy as np
import os, sys

tags = []
for i in range(1, len(sys.argv)): tags.append(sys.argv[i])

flab = []

def readDB():
    global flab

    db   = {}
    flab = []

    for tag in tags:
        file = open(tag + ".species")
        data = []
        line = file.readline()  # Label line
        labs = [v for v in line[1:].split()]
        for line in file:
            if line.find('#')<0:
                data.append([float(v) for v in line.split()])

        a = np.array(data).transpose()

        db[tag] = {}

        for i in range(a.shape[0]):
            db[tag][labs[i]] = a[i]

        for v in labs:
            if v not in flab: flab.append(v)

    return db


def makeP(lab):
    db = readDB()

    if lab not in flab:
        print "No such field, available data is:"
        icnt = 0
        for v in flab:
            icnt += 1
            print "{:10s}".format(v),
            if icnt % 6 == 0: print
        return
    
    for t in tags:
        plt.plot(db[t]['Time'], db[t][lab], '-', label=t)
    plt.legend()
    plt.xlabel('Time')
    plt.ylabel(lab)
    plt.show()
