{% set name = "pyEXP" %}
{% set version = "7.7.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file:///home/georgia/Projects/umass/unity/user_support/martin_exp/packaging/pypi/pyEXP/dist/pyEXP-7.7.28.tar.gz
  sha256: 63564ac26c59b1b5b90e823a514c215f5bf829eddc434d3c880251084cd59bd0

build:
  number: 0

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ mpi }}-mpicc
    - {{ mpi }}-mpicxx
    - {{ mpi }}-mpifort
    - setuptools >=42
    - scikit-build >=0.13
    - cmake >=3.21
    - ninja
    - pip
    - pybind11
    - eigen
    - highfive ==2.4.1
  host:
    - python
    - {{ mpi }}
    - hdf5 >=1.8.20
    - boost-cpp
    # - fftw
    # - libtirpc # [linux-64]
    # - yaml-cpp
    # - zlib
    # - libpng
    - exp-libraries =={{ version }}
  run:
    - python
    - {{ mpi }}
    # - _openmp_mutex
    - hdf5 >=1.8.20
    - boost-cpp
    # - fftw
    # - libtirpc # [linux-64]
    # - yaml-cpp
    # - libpng
    - exp-libraries =={{ version }}
about:
  summary: Nbody EXPansion Code - Libraries
  license: GPL-3.0 AND MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - georgiastuart
