#!/usr/bin/env python3

"""
Construct and view a spherical basis
"""

import os, sys, getopt
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import pyEXP

def main(prog, argv):
   """
   Construct and view a spherical basis
   """

   model = 'SLgridSph.model'
   dir   = ''
   rmin  = -1
   rmax  = -1
   Lmax  = 6
   Nmax  = 18
   knot  = 200
   show  = 8
   noLog = False

   phrase = prog + ': [-h] -f|--model=modelfile -r|--rmin arg -R|--rmax arg [-l|--lmax arg] [-n|--nmax arg] [-s|--show arg] [-k|--knots arg] [--linear]';

   try:
      opts, args = getopt.getopt(argv,"hf:d:r:R:L:n:s:",["model=","dir=", "rmin=","rmax=","lmax=","nmax=","show=", "linear"])
   except getopt.GetoptError:
      print(phrase)
      sys.exit(2)
   for opt, arg in opts:
      if opt == '-h':
         print(phrase)
         sys.exit()
      elif opt in ("-f", "--model"):
         model = arg
      elif opt in ("-d", "--dir"):
         dir = arg
      elif opt in ("-r", "--rmin"):
         rmin = float(arg)
      elif opt in ("-R", "--rmax"):
         rmin = float(arg)
      elif opt in ("-l", "--lmax"):
         Lmax = int(arg)
      elif opt in ("-n", "--nmax"):
         Nmax = int(arg)
      elif opt in ("-s", "--show"):
         show = int(arg)
      elif opt in ("-k", "--knot"):
         knot = int(arg)
      elif opt in ("--linear"):
         noLog = True

   if len(dir): os.chdir(dir)

   # Get rmin and/or rmax from the file
   get_rmax = False
   if rmax<0: get_rmax = True

   if rmin<0 or get_rmax:
      # Open and parse model file to get min and max radii
      file = open(model, 'r')
      num  = -1
      for line in file:
         if line.find('#')<0 and line.find('%')<0 and line.find('!'):
            if num<0:
               num = int(line)
            else:
               toks = line.split()
               if rmin<0:   rmin = float(toks[0])
               if get_rmax: rmax = float(toks[0])

   # 200 knots should be enough for most cases.  Try a smaller value
   # (e.g. 20) to observe the effect on the orthogonality ...
   
   # Construct the basis config for this model
   #
   bconfig = """
---
id: sphereSL
parameters :
  numr:  2000
  rmin:  {}
  rmax:  {}
  Lmax:  {}
  nmax:  {}
  scale: 0.0667
  modelname: {}
...
""".format(rmin, rmax, Lmax, Nmax, model)

   # Construct the basis instance
   #
   basis = pyEXP.basis.Basis.factory(bconfig)
   lrmin = np.log10(rmin)
   lrmax = np.log10(rmax)
   rnum  = 200
   grid  = basis.getBasis(lrmin, lrmax, rnum)

   # Make a logarithmically space grid in radius
   #
   r = np.linspace(lrmin, lrmax, rnum)
   r = np.power(10.0, r)

   # Plot the matrices as images with a greyscale color map
   #
   fig   = plt.figure(figsize=(15, 15)) 
   ncol  = 3                    # Rows with 3 columns
   nrow  = int(Lmax/ncol)
   
   if ncol*nrow <= Lmax: nrow += 1
   ax = fig.subplots(nrow, ncol, sharey=False, squeeze=True).flatten()

   l = 0                        # Harmonic index counter
   for i in range(0, nrow):
      for j in range(0, ncol):
         if l<=Lmax:
            for n in range(min(show, Nmax)):
               if noLog:
                  ax[i*ncol+j].plot(r, grid[l][n], '-')
               else:
                  ax[i*ncol+j].semilogx(r, grid[l][n], '-')
            ax[i*ncol+j].set_ylim(np.min(grid[l][n]), np.max(grid[l][n]))
            ax[i*ncol+j].set_xlabel('r')
            ax[i*ncol+j].set_ylabel('potential')
            ax[i*ncol+j].set_title('l={}'.format(l))
            l += 1
         else:
            # Remove unused frames
            fig.delaxes(ax[i*ncol+j])

   plt.tight_layout()
   plt.show()

if __name__ == "__main__":
   main(sys.argv[0], sys.argv[1:])

