# CMake generated Testfile for 
# Source directory: /home/runner/work/EXP/EXP/tests
# Build directory: /home/runner/work/EXP/EXP/_codeql_build_dir/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[pyexpLoadTest]=] "/usr/local/bin/cmake" "-E" "env" "PYTHONPATH=/home/runner/work/EXP/EXP/_codeql_build_dir/pyEXP:" "/usr/bin/python3" "import.py")
set_tests_properties([=[pyexpLoadTest]=] PROPERTIES  LABELS "quick" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;9;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[pyexpSphBasisTest]=] "/usr/local/bin/cmake" "-E" "env" "PYTHONPATH=/home/runner/work/EXP/EXP/_codeql_build_dir/pyEXP:" "/usr/bin/python3" "sph_basis.py")
set_tests_properties([=[pyexpSphBasisTest]=] PROPERTIES  LABELS "quick" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Halo" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;16;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[pyexpCylBasisTest]=] "/usr/local/bin/cmake" "-E" "env" "PYTHONPATH=/home/runner/work/EXP/EXP/_codeql_build_dir/pyEXP:" "/usr/bin/python3" "cyl_basis.py")
set_tests_properties([=[pyexpCylBasisTest]=] PROPERTIES  LABELS "long" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Disk" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;23;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[removeSphCache]=] "/usr/local/bin/cmake" "-E" "remove" ".slgrid_sph_cache")
set_tests_properties([=[removeSphCache]=] PROPERTIES  DEPENDS "pyexpSphBasisTest" REQUIRED_FILES ".slgrid_sph_cache" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Halo" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;30;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[removeCylCache]=] "/usr/local/bin/cmake" "-E" "remove" ".eof.cache.run0t")
set_tests_properties([=[removeCylCache]=] PROPERTIES  DEPENDS "pyexpCylBasisTest" REQUIRED_FILES ".eof.cache.run0t" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Disk" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;34;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[expExecuteTest]=] "mpirun" "/home/runner/work/EXP/EXP/_codeql_build_dir/src/exp" "-v")
set_tests_properties([=[expExecuteTest]=] PROPERTIES  LABELS "quick" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;56;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[makeICTest]=] "mpirun" "/home/runner/work/EXP/EXP/_codeql_build_dir/utils/ICs/gensph" "-N" "10000" "-i" "SLGridSph.model")
set_tests_properties([=[makeICTest]=] PROPERTIES  LABELS "long" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Halo" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;61;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[expNbodyTest]=] "mpirun" "/home/runner/work/EXP/EXP/_codeql_build_dir/src/exp" "config.yml")
set_tests_properties([=[expNbodyTest]=] PROPERTIES  DEPENDS "makeICTest" LABELS "long" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Halo" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;66;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[expNbodyCheck2TW]=] "/usr/local/bin/cmake" "-E" "env" "PYTHONPATH=/home/runner/work/EXP/EXP/_codeql_build_dir/pyEXP:" "/usr/bin/python3" "check.py")
set_tests_properties([=[expNbodyCheck2TW]=] PROPERTIES  DEPENDS "expNbodyTest" LABELS "long" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Halo" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;73;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[pyEXPCoefReadTest]=] "/usr/local/bin/cmake" "-E" "env" "PYTHONPATH=/home/runner/work/EXP/EXP/_codeql_build_dir/pyEXP:" "/usr/bin/python3" "readCoefs.py")
set_tests_properties([=[pyEXPCoefReadTest]=] PROPERTIES  DEPENDS "expNbodyTest" LABELS "long" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Halo" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;85;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[pyEXPCoefMatrixTest]=] "/usr/local/bin/cmake" "-E" "env" "PYTHONPATH=/home/runner/work/EXP/EXP/_codeql_build_dir/pyEXP:" "/usr/bin/python3" "changeCoefs.py")
set_tests_properties([=[pyEXPCoefMatrixTest]=] PROPERTIES  DEPENDS "expNbodyTest" LABELS "long" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Halo" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;92;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[pyEXPCoefCreateTest]=] "/usr/local/bin/cmake" "-E" "env" "PYTHONPATH=/home/runner/work/EXP/EXP/_codeql_build_dir/pyEXP:" "/usr/bin/python3" "createCoefs.py")
set_tests_properties([=[pyEXPCoefCreateTest]=] PROPERTIES  LABELS "quick" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Halo" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;99;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[removeTempFiles]=] "/usr/local/bin/cmake" "-E" "remove" "config.run0.yml" "current.processor.rates.run0" "new.bods" "OUTLOG.run0" "run0.levels" "SLGridSph.cache.run0" "test.grid" "outcoef.halo.run0" "SLGridSph.cache.run0")
set_tests_properties([=[removeTempFiles]=] PROPERTIES  DEPENDS "expNbodyCheck2TW" LABELS "long" REQUIRED_FILES "config.run0.yml;current.processor.rates.run0;new.bods;run0.levels;SLGridSph.cache.run0;test.grid;" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Halo" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;109;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[makeCubeICTest]=] "mpirun" "/home/runner/work/EXP/EXP/_codeql_build_dir/utils/ICs/cubeics" "-N" "4000" "-z" "-d" "2,2,2")
set_tests_properties([=[makeCubeICTest]=] PROPERTIES  LABELS "long" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Cube" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;122;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[expCubeTest]=] "mpirun" "/home/runner/work/EXP/EXP/_codeql_build_dir/src/exp")
set_tests_properties([=[expCubeTest]=] PROPERTIES  DEPENDS "makeCubeICTest" LABELS "long" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Cube" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;127;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[expCubeCheckPos]=] "/usr/local/bin/cmake" "-E" "env" "PYTHONPATH=/home/runner/work/EXP/EXP/_codeql_build_dir/pyEXP:" "/usr/bin/python3" "check.py")
set_tests_properties([=[expCubeCheckPos]=] PROPERTIES  DEPENDS "expCubeTest" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Cube" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;134;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[removeCubeFiles]=] "/usr/local/bin/cmake" "-E" "remove" "config.runS.yml" "current.processor.rates.runS" "cube.bods" "OUTLOG.runS" "runS.levels")
set_tests_properties([=[removeCubeFiles]=] PROPERTIES  DEPENDS "expCubeCheckPos" LABELS "long" REQUIRED_FILES "config.runS.yml;current.processor.rates.runS;cube.bods;OUTLOG.runS;runS.levels;" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests/Cube" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;143;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
add_test([=[scriptTest]=] "/home/runner/work/EXP/EXP/tests/script_test.sh")
set_tests_properties([=[scriptTest]=] PROPERTIES  LABELS "quick" WORKING_DIRECTORY "/home/runner/work/EXP/EXP/tests" _BACKTRACE_TRIPLES "/home/runner/work/EXP/EXP/tests/CMakeLists.txt;166;add_test;/home/runner/work/EXP/EXP/tests/CMakeLists.txt;0;")
