#ifndef _atomic_constants_H
#define _atomic_constants_H

// Proton mass (g)
const double mp        = 1.67262158e-24;

// Electron mass (g)
const double me        =  9.10938291e-28;

// Speed of light (cm/s)
const double light     =  2.99792458e+10;

// electron volt in (cgs)
const double eV        =  1.60217653e-12;

// Boltzmann constant (cgs)
const double boltz     = 1.3806504e-16;

// Boltzmann constant (eV)
const double boltzEv   = 8.6173324e-5;

// Planck's constant (cgs)
const double planck    = 6.626075540e-27;

// Electron charge (cgs)
const double esu       = 4.80320427e-10;

// Atomic mass unit in grams
const double amu       = 1.660539e-24;

// Electron rest mass in MeV
const double mec2      = 0.51099891013;

// Parsec (cm)
const double pc        = 3.08567758e18;

// Bohr radius (cm)
const double a0        = 0.052917721092e-7;

// Year (sec)
const double year      = 365.242*24*3600;

// Solar mass (g)
const double msun      = 1.9891e33;

#endif
