#ifndef _Global_H
#define _Global_H

#include <stdlib.h>
#include <sys/types.h>
#include <getopt.h>
#include <time.h>

#include <boost/algorithm/string.hpp>
#include <string>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <iostream>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>


// Unused globals
extern unsigned multistep;

extern double Lunit; //a box that is 1 pc per side
extern double Tunit;
extern double Vunit;
extern double Munit; //for 0.5 cm^(-3) gas in a volume of 1 pc^3

#endif
