#	rebuild all libraries

ALL:	all
all:	libnumerical.a libnumerical.so.0

#	set variant-dependent compilation flags

libnumerical.a:
	make -f Makefile.2 libnumerical.a DEBUG=1

libnumerical.so.0:
	make -f Makefile.2 libnumerical.so.0







#	set variant-dependent object directories

libnumericalg.a := VARIANT = Debug/
libnumerical.a := VARIANT = Optimised/





#	rebuild if make state has been changed


.KEEP_STATE:
.INIT: Debug Optimised
Debug Optimised:
	test -d $@ || mkdir $@


