float *vector(int, int);
float **matrix(int, int, int, int);
float **submatrix(float **, int, int, int, int);
float **convert_matrix(float *, int, int, int, int);
double *dvector(int, int);
double **dmatrix(int, int, int, int);
int *ivector(int, int);
int **imatrix(int, int, int, int);
void free_vector(float *, int, int);
void free_dvector(double *, int, int);
void free_ivector(int *, int, int);
void free_matrix(float **, int, int, int, int);
void free_submatrix(float *, int, int, int, int);
void free_convert_matrix(float **, int, int, int, int);
void free_dmatrix(double **, int, int, int, int);
void free_imatrix(int **, int, int, int, int);
void myerror(char *);
void nrerror(char *);
void spline(double *x, double *y, int n, double yp1, double ypn, double *y2);
void splint(double *xa, double *ya, double *y2a, int n, double x, double *y, double *yd, double *ydd);
void splint1(double *xa, double *ya, double *y2a, int n, double x, double *y);
void splint1d(double *xa, double *ya, double *y2a, int n, double x, double *y, double *yd, double *ydd);
double	splsum(double *x, double *y, int n);
void splsum2(double *x, double *y, double *z, int n);
